/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as STokenRouteImport } from './routes/s/$token'
import { Route as AuthPathRouteImport } from './routes/auth/$path'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedExportRouteImport } from './routes/_authenticated/export'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSongsIndexRouteImport } from './routes/_authenticated/songs/index'
import { Route as AuthenticatedShowsIndexRouteImport } from './routes/_authenticated/shows/index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedSongsNewRouteImport } from './routes/_authenticated/songs/new'
import { Route as AuthenticatedSongsIdRouteImport } from './routes/_authenticated/songs/$id'
import { Route as AuthenticatedShowsNewRouteImport } from './routes/_authenticated/shows/new'
import { Route as AuthenticatedShowsIdRouteImport } from './routes/_authenticated/shows/$id'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects/new'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects/$id'
import { Route as AuthenticatedAccountPathRouteImport } from './routes/_authenticated/account/$path'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathRoute = AuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExportRoute = AuthenticatedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSongsIndexRoute = AuthenticatedSongsIndexRouteImport.update({
  id: '/songs/',
  path: '/songs/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShowsIndexRoute = AuthenticatedShowsIndexRouteImport.update({
  id: '/shows/',
  path: '/shows/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSongsNewRoute = AuthenticatedSongsNewRouteImport.update({
  id: '/songs/new',
  path: '/songs/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSongsIdRoute = AuthenticatedSongsIdRouteImport.update({
  id: '/songs/$id',
  path: '/songs/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShowsNewRoute = AuthenticatedShowsNewRouteImport.update({
  id: '/shows/new',
  path: '/shows/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShowsIdRoute = AuthenticatedShowsIdRouteImport.update({
  id: '/shows/$id',
  path: '/shows/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountPathRoute =
  AuthenticatedAccountPathRouteImport.update({
    id: '/account/$path',
    path: '/account/$path',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/export': typeof AuthenticatedExportRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/import': typeof AuthenticatedImportRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/$path': typeof AuthPathRoute
  '/s/$token': typeof STokenRoute
  '/account/$path': typeof AuthenticatedAccountPathRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/shows/$id': typeof AuthenticatedShowsIdRoute
  '/shows/new': typeof AuthenticatedShowsNewRoute
  '/songs/$id': typeof AuthenticatedSongsIdRoute
  '/songs/new': typeof AuthenticatedSongsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/shows/': typeof AuthenticatedShowsIndexRoute
  '/songs/': typeof AuthenticatedSongsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/export': typeof AuthenticatedExportRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/import': typeof AuthenticatedImportRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/$path': typeof AuthPathRoute
  '/s/$token': typeof STokenRoute
  '/account/$path': typeof AuthenticatedAccountPathRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/shows/$id': typeof AuthenticatedShowsIdRoute
  '/shows/new': typeof AuthenticatedShowsNewRoute
  '/songs/$id': typeof AuthenticatedSongsIdRoute
  '/songs/new': typeof AuthenticatedSongsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/shows': typeof AuthenticatedShowsIndexRoute
  '/songs': typeof AuthenticatedSongsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/export': typeof AuthenticatedExportRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/$path': typeof AuthPathRoute
  '/s/$token': typeof STokenRoute
  '/_authenticated/account/$path': typeof AuthenticatedAccountPathRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/_authenticated/shows/$id': typeof AuthenticatedShowsIdRoute
  '/_authenticated/shows/new': typeof AuthenticatedShowsNewRoute
  '/_authenticated/songs/$id': typeof AuthenticatedSongsIdRoute
  '/_authenticated/songs/new': typeof AuthenticatedSongsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/shows/': typeof AuthenticatedShowsIndexRoute
  '/_authenticated/songs/': typeof AuthenticatedSongsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/export'
    | '/history'
    | '/import'
    | '/settings'
    | '/auth/$path'
    | '/s/$token'
    | '/account/$path'
    | '/projects/$id'
    | '/projects/new'
    | '/shows/$id'
    | '/shows/new'
    | '/songs/$id'
    | '/songs/new'
    | '/api/auth/$'
    | '/projects/'
    | '/shows/'
    | '/songs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/export'
    | '/history'
    | '/import'
    | '/settings'
    | '/auth/$path'
    | '/s/$token'
    | '/account/$path'
    | '/projects/$id'
    | '/projects/new'
    | '/shows/$id'
    | '/shows/new'
    | '/songs/$id'
    | '/songs/new'
    | '/api/auth/$'
    | '/projects'
    | '/shows'
    | '/songs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/export'
    | '/_authenticated/history'
    | '/_authenticated/import'
    | '/_authenticated/settings'
    | '/auth/$path'
    | '/s/$token'
    | '/_authenticated/account/$path'
    | '/_authenticated/projects/$id'
    | '/_authenticated/projects/new'
    | '/_authenticated/shows/$id'
    | '/_authenticated/shows/new'
    | '/_authenticated/songs/$id'
    | '/_authenticated/songs/new'
    | '/api/auth/$'
    | '/_authenticated/projects/'
    | '/_authenticated/shows/'
    | '/_authenticated/songs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthPathRoute: typeof AuthPathRoute
  STokenRoute: typeof STokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$path': {
      id: '/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof AuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/export': {
      id: '/_authenticated/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthenticatedExportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/songs/': {
      id: '/_authenticated/songs/'
      path: '/songs'
      fullPath: '/songs/'
      preLoaderRoute: typeof AuthenticatedSongsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shows/': {
      id: '/_authenticated/shows/'
      path: '/shows'
      fullPath: '/shows/'
      preLoaderRoute: typeof AuthenticatedShowsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/songs/new': {
      id: '/_authenticated/songs/new'
      path: '/songs/new'
      fullPath: '/songs/new'
      preLoaderRoute: typeof AuthenticatedSongsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/songs/$id': {
      id: '/_authenticated/songs/$id'
      path: '/songs/$id'
      fullPath: '/songs/$id'
      preLoaderRoute: typeof AuthenticatedSongsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shows/new': {
      id: '/_authenticated/shows/new'
      path: '/shows/new'
      fullPath: '/shows/new'
      preLoaderRoute: typeof AuthenticatedShowsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shows/$id': {
      id: '/_authenticated/shows/$id'
      path: '/shows/$id'
      fullPath: '/shows/$id'
      preLoaderRoute: typeof AuthenticatedShowsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/$path': {
      id: '/_authenticated/account/$path'
      path: '/account/$path'
      fullPath: '/account/$path'
      preLoaderRoute: typeof AuthenticatedAccountPathRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExportRoute: typeof AuthenticatedExportRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAccountPathRoute: typeof AuthenticatedAccountPathRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
  AuthenticatedShowsIdRoute: typeof AuthenticatedShowsIdRoute
  AuthenticatedShowsNewRoute: typeof AuthenticatedShowsNewRoute
  AuthenticatedSongsIdRoute: typeof AuthenticatedSongsIdRoute
  AuthenticatedSongsNewRoute: typeof AuthenticatedSongsNewRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedShowsIndexRoute: typeof AuthenticatedShowsIndexRoute
  AuthenticatedSongsIndexRoute: typeof AuthenticatedSongsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExportRoute: AuthenticatedExportRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAccountPathRoute: AuthenticatedAccountPathRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
  AuthenticatedShowsIdRoute: AuthenticatedShowsIdRoute,
  AuthenticatedShowsNewRoute: AuthenticatedShowsNewRoute,
  AuthenticatedSongsIdRoute: AuthenticatedSongsIdRoute,
  AuthenticatedSongsNewRoute: AuthenticatedSongsNewRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedShowsIndexRoute: AuthenticatedShowsIndexRoute,
  AuthenticatedSongsIndexRoute: AuthenticatedSongsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthPathRoute: AuthPathRoute,
  STokenRoute: STokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
